a=[]
x=int(input())
for i in range(x):
    val=input("enter value: ")
    a.append(val)
print("original list is: ",a)
print("lenght",len(a))
print("maximum",max(a))
print("min",min(a))
b=a 
print("content of a",a)
print("content of b",b) 
z=input("enter the value to count: ")
y=a.count(z)
print(z,"appears in list",y,"times")  
z=input("enter the value whise index yiu want to get:")
index=a.index(z)
print(z,"found at",index,"position")
val=input("enter the value: ")
ind=int(input("enter index where you want to insert:"))
a.insert(ind,val)
print(a)
val=input("enter value to remive: ")
a.remove(val)
print(a)
print("original list is: ",a)
a.reverse()
print("after reverse is",a)
a.sort()
print("list after shorting is",a)
print("last element poped: ",a.pop())